# Generated by Django 3.0.5 on 2020-04-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_auto_20200403_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa_fisica',
            name='telefone',
            field=models.CharField(default='', max_length=25),
        ),
    ]
