# Generated by Django 3.0.5 on 2020-04-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_pessoa_fisica_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='situacao',
            field=models.BooleanField(default=1),
        ),
    ]
