# Generated by Django 3.0.5 on 2020-04-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_auto_20200404_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa_fisica',
            name='dataNascimento',
            field=models.DateField(verbose_name=['%d/%m/%Y']),
        ),
    ]
