# Generated by Django 3.0.5 on 2020-04-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_auto_20200405_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa_fisica',
            name='dataNascimento',
            field=models.DateField(),
        ),
    ]
