# Generated by Django 3.0.5 on 2020-04-06 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_auto_20200405_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='avaliacoes',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='matriculas',
        ),
    ]
