# Generated by Django 3.0.5 on 2020-04-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_auto_20200405_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisioterapeuta',
            name='avaliacoes',
            field=models.ManyToManyField(related_name='avaliacoes', through='academia.Avaliacao', to='academia.Cliente'),
        ),
        migrations.AddField(
            model_name='plano',
            name='matriculas',
            field=models.ManyToManyField(related_name='matriculas', through='academia.Matricula', to='academia.Cliente'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='ferias',
            field=models.ManyToManyField(related_name='ferias', through='academia.Parcela', to='academia.Ferias'),
        ),
    ]
