# Generated by Django 3.0.5 on 2020-04-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0008_auto_20200405_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='referencia',
            field=models.CharField(default=None, max_length=7),
        ),
    ]
