# Generated by Django 3.0.5 on 2020-04-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0013_remove_pagamento_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='referencia',
            field=models.CharField(default='2020-4', max_length=7),
        ),
    ]
