# Generated by Django 3.0.5 on 2020-04-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0015_auto_20200407_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='referencia',
        ),
    ]
