# Generated by Django 3.0.5 on 2020-04-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0017_pagamento_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='referencia',
            field=models.CharField(default='4-2020', max_length=7),
        ),
    ]
