# Generated by Django 3.0.5 on 2020-04-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0018_auto_20200407_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferias',
            name='id',
        ),
        migrations.AlterField(
            model_name='ferias',
            name='anoReferencia',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
