# Generated by Django 3.0.5 on 2020-04-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0019_auto_20200410_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='ferias',
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='ferias',
        ),
    ]
