# Generated by Django 3.0.5 on 2020-04-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0020_auto_20200410_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='ferias',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='academia.Ferias'),
        ),
    ]
