# Generated by Django 3.0.5 on 2020-04-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0021_parcela_ferias'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='ferias',
            field=models.ManyToManyField(related_name='ferias', through='academia.Parcela', to='academia.Ferias'),
        ),
    ]
